package com.ifp.util;

public class SQLConstants {
	
	private static final String pers_card_process_query="INSERT INTO PERS_CARD_PROCESS(INST_ID,ORDER_REF_NO,CARD_TYPE_ID,ACCTTYPE_ID,"
			+ "ACCTSUB_TYPE_I,ACC_CCY,ACCOUNT_NO,SUB_PROD_ID,PRODUCT_CODE,LIMIT_ID,FEE_CODE,CARD_QUANTITY,ORDER_STATUS,ORDER_TYPE,ORDERED_DATE,"
			+ "ORDERED_TIME,EMBOSSING_NAME,MKCK_STATUS,REMARKS,ENCODE_DATA,MAKER_DATE,MAKER_TIME,MAKER_ID,CHECKER_DATE,"
			+ "CHECKER_TIME,CHECKER_ID,BRANCH_CODE,BIN,APP_DATE,CIN,APP_NO,KYC_FLAG,APPTYPE,CARDISSUETYPE,PARENTCARD,LIMIT_BASEDON,"
			+ "REG_LEVEL,AUTH_DATE,RENEWALFLAG,"
			+ "CARD_COLLECT_BRANCH) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";


}
