/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2022-08-26 07:28:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import sun.misc.BASE64Decoder;

public final class baseLayoutmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/E:/GIT_WORKSPACE/SIB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SIB/WEB-INF/lib/tiles-jsp-2.1.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1233468994000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.1.2.jar", Long.valueOf(1659502811640L));
    _jspx_dependants.put("jar:file:/E:/GIT_WORKSPACE/SIB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SIB/WEB-INF/lib/struts2-core-2.1.6.jar!/META-INF/struts-tags.tld", Long.valueOf(1231165946000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.1.6.jar", Long.valueOf(1659502809945L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("sun.misc.BASE64Decoder");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta http-equiv=\"Cache-control\" content=\"no-cache\"/>\r\n");
      out.write("<meta http-equiv=\"Cache-control\" content=\"no-store\"/>\r\n");
      out.write("<meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery/base64.js\"></script>  \r\n");
      out.write(" <LINK REL=\"SHORTCUT ICON\" HREF=\"images.ico\">\r\n");
      out.write("   \r\n");
 
int applying_width = 900; 
int applying_height = 350;
//out.println( "ifp__" + request.getParameter("ifp")  );
if( request.getParameter("ifp") == null ) {// out.println( "null true ");  
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script language=\"Javascript\" type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t$(\"ul.dropdown ul\").mouseover(function(){\r\n");
      out.write("\t\t\t  var visiblewidth = $('body').innerWidth();\r\n");
      out.write("\t\t\t  var submenuleft= $(this).find(\"ul\").offset();\t\t\t\r\n");
      out.write("  \t\t\t  var submenuwidth= $(this).find(\"ul\").width();\t\t\t\r\n");
      out.write("\t\t\t  var newsubmenupos=submenuleft.left+submenuwidth;\t\t\t  \r\n");
      out.write("\t\t\t  if (newsubmenupos>visiblewidth)\r\n");
      out.write("\t\t\t\t\t\t\t$(this).find(\"ul\").css({\"left\":\"-99%\"});\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\">  \r\n");
      out.write("\tvar scr_width = encode64(screen.width);\r\n");
      out.write("\tvar scr_height = encode64(screen.height); \r\n");
      out.write("\tvar width = encode64(\"width\");\r\n");
      out.write("\tvar height= encode64(\"height\");\r\n");
      out.write("\t \r\n");
      out.write("\tvar url = \"instUserHomeAction.do?ifp=\"+width+\"/\"+scr_width+\"/\"+height+\"/\"+scr_height;\r\n");
      out.write("\t//var url = \"instUserHomeAction.do?john=\";\r\n");
      out.write("\t //alert(url);\r\n");
      out.write("\twindow.location = url;\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
 } else {

	try{
	response.setHeader( "Pragma", "no-cache" );
  	response.setHeader( "Cache-Control", "no-cache" );
  	response.setDateHeader( "Expires", 0 ); 
  
 	
   
	BASE64Decoder decoder = new BASE64Decoder();
   
	String urlparam =  request.getParameter("ifp");
	String[] params = urlparam.split("/"); 
	String txt_width = params[0];
	String width_val = params[1];
	String txt_height=params[2];
	String height_val = params[3]; 
  
	// out.println("urlparam_ " + urlparam +"<br/>");
	 
	 byte[] widthtxt = decoder.decodeBuffer(txt_width); 
	 String caption_width = new String(widthtxt, "UTF-8");  
	 
	 byte[] height_txt = decoder.decodeBuffer(txt_height); 
	 String caption_height = new String(height_txt, "UTF-8");  
	 
	 
	 
	 byte[] widthval = decoder.decodeBuffer(width_val); 
	 String scr_width = new String(widthval, "UTF-8");  
	 applying_width = Integer.parseInt(scr_width)-40;
	 
	 byte[] hieghtval = decoder.decodeBuffer(height_val);
	 String scr_height = new String(hieghtval, "UTF-8");  
	 applying_height = Integer.parseInt(scr_height)-350;
	 
	 // out.println("screen width is " + applying_width);
	}catch(Exception e ){
		out.println("Exception " + e );
		//session.invalidate();
	
      out.write("\t<script>\r\n");
      out.write("\t\t\tvar url = \"logoutAction.do?msg=invalid url modification\";\r\n");
      out.write("\t\t\twindow.location=url;\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t");

	}
   } 

//out.println( "applying_height__" + applying_height );

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("            <!-- <title>IFP:");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write(" </title> -->\r\n");
      out.write("            <!-- <title>UTBL Bank</title> -->\r\n");
      out.write("            <title>SIB Bank</title> \r\n");
      out.write("            <link href=\"style/ifps.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("            <link href=\"style/dropdown.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("            <link href=\"style/default.css\" rel=\"stylesheet\" type=\"text/css\"> \r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"style/jquery_css.css\">\r\n");
      out.write("\t\t\t<script src=\"js/jquery/jquery.js\"  type=\"text/javascript\"  ></script>\r\n");
      out.write("\t\t\t<script src=\"js/jquery/jquery-ui.js\"  type=\"text/javascript\"  ></script>\r\n");
      out.write("\t\t\t<script src=\"js/processing.js\"></script>\r\n");
      out.write("\t\t\t<link href=\"style/processing.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write(" \r\n");
      out.write(" var isClose = false;\r\n");
      out.write(" //this code will handle the F5 or Ctrl+F5 key\r\n");
      out.write(" //need to handle more cases like ctrl+R whose codes are not listed here\r\n");
      out.write("\r\n");
      out.write(" document.onkeydown = checkKeycode();\r\n");
      out.write(" function checkKeycode(e) \r\n");
      out.write(" {\t\r\n");
      out.write("\t var keycode;\r\n");
      out.write("\t if (window.event)\r\n");
      out.write("\t \t{\r\n");
      out.write("\t\t keycode = window.event.keyCode;\r\n");
      out.write("\t\t alert(\"Key pressed\");\r\n");
      out.write("\t \t alert(keycode);\r\n");
      out.write("\t \t}\r\n");
      out.write("\t else if (e)\r\n");
      out.write("\t \tkeycode = e.which;\r\n");
      out.write("\t if(keycode == 116)\r\n");
      out.write("\t {\r\n");
      out.write("\t\t alert(\"Key pressed\");\r\n");
      out.write("\t \tisClose = true;\r\n");
      out.write("\t } \r\n");
      out.write("\t \r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function somefunction()\r\n");
      out.write(" {\r\n");
      out.write(" \tisClose = true;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function doUnload()\r\n");
      out.write(" {\r\n");
      out.write(" \tif(!isClose)\r\n");
      out.write("\t {\r\n");
      out.write("\t \talert('window is closing');\r\n");
      out.write("\t }\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function noBack() { \r\n");
      out.write("\t\t\r\n");
      out.write("\t\twindow.history.forward(); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" function center  () {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar top, left;\r\n");
      out.write("\t\t//alert(\"model\"+$(\"#modal\").height());\r\n");
      out.write("\t\t//alert(\"body\"+$(\"body\").height());\r\n");
      out.write("\t\ttop = Math.max($(\"body\").height() - $(\"#modal\").height(), 0) / 2;\r\n");
      out.write("\t\tleft = Math.max($(\"body\").innerWidth() - $(\"#modal\").outerWidth(), 0) / 2;\t\r\n");
      out.write("\t\t//alert(\"top\"+top);\r\n");
      out.write("\t\t$(\"#modal\").css({\r\n");
      out.write("\t\t\ttop:top + $(window).scrollTop(), \r\n");
      out.write("\t\t\tleft:left + $(window).scrollLeft()\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#popdivpos\").css(\"padding-bottom\",\"0px\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(" \r\n");
      out.write(" $(document).ready(function(){\r\n");
      out.write(" \t$( \"#modal\").draggable();\r\n");
      out.write(" \t$( \"#modal\").resizable();\r\n");
      out.write(" \t$(\"#close\").click(function(e){\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t$(\"#modal\").hide();\r\n");
      out.write("\t\t$(\"#overlay\").hide();\r\n");
      out.write("\t\t$(\"#content\").empty();\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t $(\"#model\").load(function(){\r\n");
      out.write("\t\t\t    alert(\"Image loaded.\");\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write(" }); \r\n");
      out.write(" //var allvalsarry = [];\r\n");
      out.write("var allvalsarry=[];\r\n");
      out.write("var mailtoarryindex;\r\n");
      out.write("var loadintextarea;\r\n");
      out.write("function updateTextArea() { \r\n");
      out.write("\t//alert(\"index \"+ mailtoarryindex);\r\n");
      out.write("\t$('#content :checked').each(function(i) {\t\r\n");
      out.write("\t\t//alert(\"total array\"+allvalsarry);\r\n");
      out.write("\t\tallvalsarry[mailtoarryindex].push((i!=0?\"\":\"\")+ $(this).val());\r\n");
      out.write("   });\r\n");
      out.write("\t//alert(\"index value\"+mailtoarryindex);\r\n");
      out.write("   //alert(\"load textarea\"+loadintextarea);\r\n");
      out.write("   //alert(\"array values \"+ allvalsarry[mailtoarryindex]);\r\n");
      out.write("   window.frames['mainframe'].document.getElementById(loadintextarea).value=allvalsarry[mailtoarryindex];   \r\n");
      out.write("   \t$(\"#modal\").hide();\r\n");
      out.write("\t$(\"#overlay\").hide();\r\n");
      out.write("\t$(\"#content\").empty();\t\r\n");
      out.write("\t\t // $('#video0_tags').val(allVals).attr('rows',allVals.length) ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function() {\r\n");
      out.write("      $('#content input').click(updateTextArea);\r\n");
      out.write("      updateTextArea();\r\n");
      out.write("});\r\n");
      out.write("</script> \r\n");
      out.write("  <!-- \r\n");
      out.write("   <SCRIPT language=\"JavaScript\"> \r\n");
      out.write("\t\t BEGIN HIDING\r\n");
      out.write("\t\tvar browserName=navigator.appName;\r\n");
      out.write("\t\tvar browserVer=parseInt(navigator.appVersion);\r\n");
      out.write("\t\tif ((browserName==\"Netscape\" && browserVer>=3) || (browserName==\"Microsoft Internet Explorer\" && browserVer>=4)) version=\"n3\";\r\n");
      out.write("\t\telse version=\"n2\"; if (version==\"n3\") alert(\"Your browser passes the test\");\r\n");
      out.write("\t\telse  window.location=\"logoutAction.do\"; \r\n");
      out.write("\t\t \r\n");
      out.write("\t</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\t-->\r\n");
      out.write("\t\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("table.globaltable{\r\n");
      out.write(" \tmargin: 0 auto; \r\n");
      out.write("\twidth :");
      out.print(applying_width);
      out.write("px; \r\n");
      out.write("}\r\n");
      out.write("#modal:hover{\r\n");
      out.write("\tcursor:move;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write(" </head>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");

String apptype =  (String)session.getAttribute("APPLICATIONTYPE"); 
String bg = "";
if(apptype.equals("PREPAID")){
	bg = "images/header_pixel.jpg";
}else if( apptype.equals("MERCHANT")){
	bg = "images/merch_onepix.gif";
}else if( apptype.equals("CREDIT")){
	bg = "images/credit_pixel.jpg";
}else if( apptype.equals("BOTH")){
	bg = "images/header_pixel.jpg";
}else{
	bg = "images/one-pix-bic.jpg";
}



      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <body class=\"background\" onload=\"noBack()\">  \r\n");
      out.write(" <!--  <body onbeforeunload=\"doUnload();\" onmousedown=\"somefunction();\"> prito -->\r\n");
      out.write(" \r\n");
      out.write("<!-- <body onbeforeunload=\"ConfirmClose();\" onunload=\"HandleOnClose();\" >  -->\r\n");
      out.write("            <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" width=\"100%\" class=\"globaltable\" id=\"globaltable\">\r\n");
      out.write("        \t\r\n");
      out.write("        \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"background:url(");
      out.print(bg);
      out.write(")\" align=\"center\">\r\n");
      out.write("                  ");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                \t<div class=\"top-bar\">\r\n");
      out.write("                \t\t<div class=\"logout\">\r\n");
      out.write("                    \t");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \t</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      if (_jspx_meth_tiles_005finsertAttribute_005f3(_jspx_page_context))
        return;
      out.write("  \r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("        \t\t<td class=\"formtitle\" id=\"title\"> \r\n");
      out.write("        \t\t <!-- ");
      if (_jspx_meth_tiles_005finsertAttribute_005f4(_jspx_page_context))
        return;
      out.write("  -->\t\r\n");
      out.write("        \t\t</td>\r\n");
      out.write("        \t</tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("               <td id=\"popdivpos\">\r\n");
      out.write("               \t<div id=\"overlay\" class=\"overlay\" style=\"display:none\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"modal\" style=\"display:none\">\r\n");
      out.write("\t\t\t\t\t<a id=\"close\" href=\"#\">close</a>\r\n");
      out.write("\t\t\t\t\t<div id=\"content\">text cin</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"process_mask\" class=\"mask\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"process\">\r\n");
      out.write("\t\t\t\t\t<div id=\"processimg\"><img src=\"images/loading/Processing.gif\" width=\"250\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"clear\"></div>\r\n");
      out.write("\t\t\t\t\t<table border='0' cellpadding='0' cellspacing='0' width='100%'>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/curve_images_red/cur_top_lef.jpg\" ></td>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100%\" background=\"images/curve_images_red/cur_top_bg.jpg\"><img src=\"images/spacer.gif\" width=\"1\" height=\"29\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/curve_images_red/cur_top_rig.jpg\" ></td>\r\n");
      out.write("\t\t\t\t   </tr>\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t    <td background=\"images/curve_images_red/cur_lef_bg.jpg\"><img src=\"images/spacer.gif\" width=\"33\" height=\"1\"></td>\r\n");
      out.write("\t\t\t\t\t    <td style=\"height:");
      out.print(applying_height);
      out.write("px;\">\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t<iframe onload=\"hideprocessing()\"\r\n");
      out.write("\t\t\t\t\t\t\tname='mainframe' \r\n");
      out.write("\t\t\t\t\t\t\tid='mainframe' \r\n");
      out.write("\t\t\t\t\t\t\twidth='100%' \r\n");
      out.write("\t\t\t\t\t\t\tsrc='' \r\n");
      out.write("\t\t\t\t\t\t\tframeborder=0 \r\n");
      out.write("\t\t\t\t\t\t\tscrolling='auto' \r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"  \r\n");
      out.write("\t\t\t\t\t\t\t\t\ttop:20%; \r\n");
      out.write("\t\t\t\t\t\t\t\t\tleft:1%; \r\n");
      out.write("\t\t\t\t\t\t\t\t\theight:");
      out.print(applying_height-10);
      out.write("px;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tposition:inherit; \r\n");
      out.write("\t\t\t\t\t\t\t\t\tz-index:0;\r\n");
      out.write("\t\t\t\t\t\t\t\t\toverflow:auto\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\">\r\n");
      out.write("\t\t\t\t\t\t</iframe>\t\r\n");
      out.write("\t\t\t\t\t \t\t\t\t\r\n");
      out.write("\t\t\t\t\t   </td>\r\n");
      out.write("\t\t\t\t\t    <td background=\"images/curve_images_red/cur_rig_bg.jpg\"><img src=\"images/spacer.gif\" width=\"38\" height=\"1\"></td>\r\n");
      out.write("\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  <tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/curve_images_red/cur_bot_lef.jpg\" ></td>\r\n");
      out.write("\t\t\t\t\t\t<td background=\"images/curve_images_red/cur_bot_bg.jpg\"><img src=\"images/spacer.gif\" width=\"1\" height=\"29\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"images/curve_images_red/cur_bot_rig.jpg\" ></td>\r\n");
      out.write("\t\t\t\t\t  </tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t </table> \r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("                \t \r\n");
      out.write("                    ");
      if (_jspx_meth_tiles_005finsertAttribute_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                </td>\r\n");
      out.write("            </tr> -->\r\n");
      out.write("        </table>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f0.setParent(null);
    // /tiles/baseLayoutmain.jsp(101,28) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setName("title");
    // /tiles/baseLayoutmain.jsp(101,28) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f0.setIgnore(true);
    int[] _jspx_push_body_count_tiles_005finsertAttribute_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005finsertAttribute_005f0 = _jspx_th_tiles_005finsertAttribute_005f0.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005finsertAttribute_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005finsertAttribute_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005finsertAttribute_005f0.doFinally();
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f1.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f1.setParent(null);
    // /tiles/baseLayoutmain.jsp(267,18) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f1.setName("header");
    int[] _jspx_push_body_count_tiles_005finsertAttribute_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005finsertAttribute_005f1 = _jspx_th_tiles_005finsertAttribute_005f1.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005finsertAttribute_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005finsertAttribute_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005finsertAttribute_005f1.doFinally();
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f2.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f2.setParent(null);
    // /tiles/baseLayoutmain.jsp(274,21) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f2.setName("top");
    int[] _jspx_push_body_count_tiles_005finsertAttribute_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005finsertAttribute_005f2 = _jspx_th_tiles_005finsertAttribute_005f2.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005finsertAttribute_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005finsertAttribute_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005finsertAttribute_005f2.doFinally();
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f3 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f3.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f3.setParent(null);
    // /tiles/baseLayoutmain.jsp(282,20) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f3.setName("menu");
    int[] _jspx_push_body_count_tiles_005finsertAttribute_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005finsertAttribute_005f3 = _jspx_th_tiles_005finsertAttribute_005f3.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005finsertAttribute_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005finsertAttribute_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005finsertAttribute_005f3.doFinally();
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f4 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f4.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f4.setParent(null);
    // /tiles/baseLayoutmain.jsp(288,16) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f4.setName("title");
    // /tiles/baseLayoutmain.jsp(288,16) name = ignore type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f4.setIgnore(true);
    int[] _jspx_push_body_count_tiles_005finsertAttribute_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005finsertAttribute_005f4 = _jspx_th_tiles_005finsertAttribute_005f4.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005finsertAttribute_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005finsertAttribute_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005finsertAttribute_005f4.doFinally();
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fignore_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f5 = (org.apache.tiles.jsp.taglib.InsertAttributeTag) _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.InsertAttributeTag.class);
    _jspx_th_tiles_005finsertAttribute_005f5.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005finsertAttribute_005f5.setParent(null);
    // /tiles/baseLayoutmain.jsp(350,20) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005finsertAttribute_005f5.setName("footer");
    int[] _jspx_push_body_count_tiles_005finsertAttribute_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005finsertAttribute_005f5 = _jspx_th_tiles_005finsertAttribute_005f5.doStartTag();
      if (_jspx_th_tiles_005finsertAttribute_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005finsertAttribute_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005finsertAttribute_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005finsertAttribute_005f5.doFinally();
      _005fjspx_005ftagPool_005ftiles_005finsertAttribute_0026_005fname_005fnobody.reuse(_jspx_th_tiles_005finsertAttribute_005f5);
    }
    return false;
  }
}
