<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%> 
<%@taglib uri="/struts-tags" prefix="s" %> 


<link rel="stylesheet" type="text/css" href="style/calendar.css"/>

<script type="text/javascript" src="js/script.js"></script> 
<script type="text/javascript" src="jsp/instant/script/ordervalidation.js"></script> 
<script type="text/javascript" src="js/calendar.js"></script>
  <script>
  
  function resetProduct( instid ){  
	  //alert(filetype);
		var filetype = document.getElementById("filetype");
		var selprodid= document.getElementById("cardtype").value;
		if( selprodid != "-1" ){
			prodid = selprodid; 
	 		var url = "getPREFilesInstCardPREProcess.do?instid="+instid+"&prodid="+prodid+"&filetype="+filetype.value;
	 		//alert(url);
	 		result = AjaxReturnValue(url);  
	 		document.getElementById("prefilename").innerHTML = result;  
		}
	}
  
  
 	function getPREFiles( instid, selprodid )
 	{  
 		var filetype = document.getElementById("filetype");		
 		var branch = document.getElementById("branchcode");
 		var filetype = document.getElementById("filetype");
 		var prodid = document.getElementById("prodid");
 		
 		 
 		if(branch.value == "-1")
 		{
 			errMessage( branch, "Please Select Branch " );
 			return false;	
 		}
 		if( selprodid != "-1" ){
 			prodid = selprodid; 
	 		var url = "getPREFilesInstCardPREProcess.do?instid="+instid+"&prodid="+prodid+"&filetype="+filetype.value;
	 		 alert(url);
	 		result = AjaxReturnValue(url);  
	 		document.getElementById("prefilename").innerHTML = result;  
	 		document.getElementById("prefileview").style.display="none";  
 		}
 	} 	
 	function getFileDetails( instid, filename ){
		 
 		var prodid = document.getElementById("cardtype"); 
 		var url = "getPREFilesDetailsInstCardPREProcess.do?instid="+instid+"&filename="+filename+"&prodid="+prodid.value;
 		 
 		result = AjaxReturnValue(url);
 		 
 		//document.getElementById("prefilename").innerHTML = result; 
 		
 		 var jsonobj = JSON.parse(result);  
 		if( jsonobj["RESP"] != 0 ){
 			document.getElementById("prefileview").style.display="none";
 			document.getElementById("prefileview").innerHTML = "";
 		}else{
 			document.getElementById("prefileview").style.display="block";
 			 
			var divblock =" <table border='0' width='130%' cellpadding='0' cellspacing='0'>";
			divblock +="		<tr><td> Selected File name </td><td style='text-align:left'> : "+jsonobj["PRENAME"]+" </td></tr> ";
			divblock +="		<tr><td> No.of Cards Contains </td><td  style='text-align:left'> : "+jsonobj["CARDCOUNT"]+" </td></tr>";
			divblock +="		<tr><td> Generated By  </td><td  style='text-align:left'> : "+jsonobj["USERNAME"]+" </td></tr>";
			divblock +="		<tr><td> Generated Date  </td><td  style='text-align:left'> : "+jsonobj["GENDATE"]+" </td></tr>";
			divblock +="		<tr><td> Download Status </td><td  style='text-align:left'> : "+jsonobj["DOWNCNT"]+" time(s) downloaded </td></tr>";
			divblock +="	<tr><td colspan='2' onclick=showCards("+"'"+filename+"'"+")>   View List of cards  </td></tr>";
			divblock +="	</table>";
			divblock +="	</div>";
			
			document.getElementById("prefileview").innerHTML=divblock;
 		}
 	}
 	
 	
 	function showCards( filename ){
 	 	 
 		var url = "getPREFileListInstCardPREProcess.do?filename="+filename;   
 		result = AjaxReturnValue(url);  
 		alert( result );
 		
 	}
 	
 	function deletePerzonalize(){
 		if( confirm ("Do you want to delete...") ){
	 		var prefilename = document.getElementById("prefilename");
	 		var url = "deleteInstPreFileInstCardPREProcess.do?prefilename="+prefilename.value; 		
	 		window.location = url;
	 		parent.showprocessing();
 		}
 		return false;
 	}
 </script>

<jsp:include page="/displayresult.jsp"></jsp:include>

<%
	String instid = (String)session.getAttribute("Instname");
	String branch = (String)session.getAttribute("BRANCHCODE");
	String branchname = (String)session.getAttribute("BRANCH_DESC");
	String usertype = (String)session.getAttribute("USERTYPE");
%>
 
<s:form action="downInstPREFilesInstCardPREProcess"  name="orderform" onsubmit="parent.showprocessing()" autocomplete = "off"  namespace="/">
 
<table border="0" cellpadding="0" cellspacing="0" width="75%" class="">	 
	 
	 
	<tr bgcolor="#3197e0" align="center">
                    <td > Select Branch</td>
                        <td >Product</td>
                    <td > File Name</td>
                 
                    <td > File Name</td>
                    
                    </tr>
                    
                    
                    <tr>
                    
               
	                   
	<%if(usertype.equals("INSTADMIN"))
		{
	%>
				<td> <s:select name="branchcode" id="branch" listKey="BRANCH_CODE" listValue="BRANCH_NAME" list="branchlist"  headerValue="Select Branch" headerKey="-1" tooltip="Select Branch"/>
						
	<%	
		}
				else
				{
			%>
					
					
					<td> : <%out.println( session.getAttribute("BRANCH_DESC") ); %></td>
						<s:hidden name="branchcode" id="branchcode" value="%{#session.BRANCHCODE}" />
					
			<%		
				}
			%>
			
			
		
		
    	
		<td> :
				
 				<select name="cardtype" id="cardtype" onchange="getPREFiles('<%=instid%>', this.value)" >
 				<option value="-1~-1">--Select -- </option>
 				<s:iterator  value="prodlist">
 				<option value="${PRODUCT_CODE}">${CARD_TYPE_NAME}</option>
 				</s:iterator>
 				</select>
		</td>
		
		
		<td> :  <select name="filetype" id="filetype" onchange="resetProduct('<%=instid%>')">
					<option value="-1"> -SELECT- </option>
					<option value="$NEW"> New File </option>
					<option value="$EXIST"> Already Downloaded File </option>
					<option value="$ALL"> ALL Files </option>  
 				</select>
		</td>
		
		
		<td> :  <select name="prefilename" id="prefilename" onchange="getFileDetails('<%=instid%>',this.value)" > 
 				</select>
		</td>
		
   
          
	

	</tr>
	
	<tr>
	
	</tr>
	
	<tr>
	
	</tr>
	
	<tr>
	
	
	<td><td> <td id='prefileviewtd'> 
	
			 <div style='border:1px solid gray; width:80%;align:right;display:none' id='prefileview'>
			 </div>
			 </td></td></td>
	
	</tr>
</table>
	 
	
	 
	  
    
	
    


<table border="0" cellpadding="0" cellspacing="4" width="20%" >
		<tr>
		<td>
			<s:submit value="Download" name="submit" id="order" onclick="return validFilter()"/>
		</td>
		<td>
			<input type="button" name="cancel" id="cancel" value="Cancel"  class="cancelbtn"  onclick="return confirmCancel()"/>
			 
		</td>
		
		<td>
		<input type="button" name="delete" id="delete" value="Delete" onclick="return deletePerzonalize()"  />
		</td>
		
		
		</tr>
</table>
</s:form>
 
 