<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%> 
<%@taglib uri="/struts-tags" prefix="s" %> 
<script type="text/javascript" src="js/script.js"></script>
 

<jsp:include page="/displayresult.jsp"></jsp:include>
<script type="text/javascript">
function validFilter(){
	var bin = document.getElementById("bin");
	if(bin){
		if(bin.value == "-1"){
			errMessage(bin,"Please Select BIN");
			return false;		
		}
	}
}

</script>
<%
	String instid = (String)session.getAttribute("Instname");
	String branch = (String)session.getAttribute("BRANCHCODE");
	String usertype = (String)session.getAttribute("USERTYPE");
	String branchname = (String)session.getAttribute("BRANCH_DESC");
	String datefilter_req = (String)session.getAttribute("DATEFILTER_REQ"); 
%>
 
<s:form action="prepaidTxnFileGenerateReconPrepaid.do"  name="orderform" onsubmit="parent.showprocessing()" autocomplete = "off"  namespace="/">
  
<table border="0" cellpadding="0" cellspacing="4" width="90%" class="formtable" style="text-align:center" >
		<tr><th> Bin </th><th> Last Reconcilation  File Generated </th><th> File Generated By</th></tr>
		<s:iterator value="reconbean.reconhistory">
			<tr> <td> ${BINDESC} </td> <td> ${LAST_GENDATE } </td> <td> ${USERNAME } </td></tr>
		</s:iterator>
        <tr>
        	<td colspan="3">
        		 <table border='0' cellpadding='0' cellspacing='0' width='20%'>
        		 <tr> <td> Bin </td> 
        		 <td>
				 
					<s:select name="bin" id="bin" listKey="BIN" listValue="BIN_DESC" list="reconbean.binlist"  headerValue="-select-" headerKey="-1" value="%{BIN_DESC}" tooltip="Select BIN"/>
				</td> </tr>
        		 </table>
        	</td>
        </tr> 
</table>
<table border='0' cellpadding='0' cellspacing='0' width='20%'>
	<tr>
		<td>
			<s:submit value="Submit" name="order" id="order" onclick="return validFilter()"/>
		</td>
		<td>
			<input type="button" name="cancel" id="cancel" value="Cancel"  class="cancelbtn"  onclick="return confirmCancel()"/>
			 
		</td>
		</tr>
</table>
</s:form>
 
 