<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%@page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%> 
<%@taglib uri="/struts-tags" prefix="s" %> 

 
<script type="text/javascript" src="js/script.js"></script> 
<script type="text/javascript" src="jsp/personalize/script/PersonalCardOrder.js"></script> 
 <jsp:include page="/displayresult.jsp"></jsp:include>

<link rel="stylesheet" type="text/css" href="style/calendar.css"/>
<script type="text/javascript" src="js/calendar.js"></script>

<script>
function validateForm(){
	var couriercompanyid = document.getElementById("couriercompanyid");
	var courierid = document.getElementById("courierid");
	var sendingaddress = document.getElementById("sendingaddress");
	var courierdate = document.getElementById("courierdate");
	if( couriercompanyid ){
		if( couriercompanyid.value == "-1"){ errMessage(couriercompanyid, "Select Courier"); return false;}
	}
	if( courierid ){
		if( courierid.value == ""){ errMessage(courierid, "Enter Courier Track Id"); return false;}
	}
	if( sendingaddress ){
		if( sendingaddress.value == ""){ errMessage(sendingaddress, "Enter Delivery Address"); return false;}
	}
	if( courierdate ){
		if( courierdate.value == ""){ errMessage(courierdate, "Select Courier Date"); return false;}
	}
	
	//if( !confirm ("Please be confirm the courier details. Once submit cannot undo it") ){
	//	return false;
	}
	
	return true;
}
</script>
<div align="center">
<s:form action="issueCardProcessActionPersonalCardReceiveIssueAction"  name="authrizeorder" onsubmit="parent.showprocessing()" autocomplete = "off"  namespace="/">
<!-- confirmCardissueorders -->
<%String act = request.getParameter("act")==null?"":request.getParameter("act"); %>
<input type="hidden" name="act" value="<%=act%>" />
	<table width="90%" cellpadding="0"  border="0"  cellspacing="0"  class="formtable"  >
	 
		<s:if test="iscouriertrackenabled">
				<tr>
					<td colspan='9'>
					<table border='1' cellpadding='0' cellspacing='0' width='100%'   >
					<tr>
						<td> Courier  : <s:select name="couriercompanyid" id="couriercompanyid" listKey="COURIERMASTER_ID" listValue="COURIER_NAME" list="courierlist"  headerValue="Select Courier" headerKey="-1"  /> </td>
					
						<td> Courier Id : <s:textfield  name="courierid" id="courierid"  /> </td>
					</tr>
					<tr valign="top">
						<td > To Agent/Address  : <br/> <s:textarea name="sendingaddress" id="sendingaddress" style="height:50px"/> </td>
					
						<td > Courier Date  :  
							<input type="text" name="courierdate" id="courierdate"  readonly="readonly" value="" onchange="return yearvalidation(this.id);" style="width:160px">
							<img src="style/images/cal.gif" id="image" onclick="displayCalendar(document.authrizeorder.courierdate,'dd-mm-yy',this);" title="Click Here to Pick up the date" border="0" width="15" height="17">
						</td>
					</tr>
					</table>
					</td>
				</tr>
			</s:if>
			<tr>
						<th> Sl no </th>
						<th>  <input type='checkbox' onclick="checkedAll(this.form)"  id="checkall"/> </th>
						<th> Order Ref No </th>
						<th> Card Number </th>
						<th> Account No </th>
						<th> Name </th>						
						<th> Product Name </th>
						<th> Generated Date </th>
						<th> Generated by </th> 
					</tr>
				<% int rowcnt = 0; Boolean alt=true; %> 
				<s:iterator value="cardissueorderlist" status="incr">
					<tr
					<% if (alt) { out.println( "class='alt'" );alt=false;}else{ alt=true;}  int rowcount = ++rowcnt; %>
					>
						<td> <%= rowcount %> </td>
						<td> <s:checkbox name="personalrefnum"  id="personalrefnum%{#incr.index}" fieldValue="%{ORG_CHN}"/>  </td>
						<td> ${ORDER_REF_NO}  </td>
						<td> ${MCARD_NO}  </td>
						<td> ${ACCT_NO}  </td>
						<td> ${EMB_NAME}  </td>
						<td> ${ PNAME }  </td>
						<td> ${GENDATE} </td> 
						<td> ${ USERNAME }</td>
					</tr>  
					<input type="hidden" name="binno" id="binno" value="${BIN}"> 
			 	</s:iterator>
			 	
			 		<tr>
						<td colspan="8">
							<s:submit name="authorize" id="authorize" value=" Process " onclick="return selectallvalidationFromIndex();" />
						 
							<input type="button" name="cancel" id="cancel" class="cancelbtn" value="Cancel" onclick="return confirmCancel()"/>
						</td>
					</tr>
	 	</table> 
	
</s:form>
</div>
 