<%@taglib uri="/struts-tags" prefix="s" %>
<%@page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<head>
<link rel="stylesheet" type="text/css" href="style/calendar.css"/>
<script type="text/javascript" src="js/calendar.js"></script>
<script type="text/javascript" src="js/script.js"></script>
<script type="text/javascript" src="jsp/personalize/script/PersonalCardOrder.js"></script>


 <script>
 	function resetProduct( instid ){
 		//alert("Resetting product");
 		var product = document.getElementById("cardtype"); 
 		var branch = document.getElementById("branchcode");
 		var filetype = document.getElementById("filetype");
 		if(branch.value == "-1")
 		{
 			errMessage( branch, "Please Select Branch " );
 			return false;	
 		}
 		
 		prodid = product.value; 
 		if( prodid != "-1" )
 		{
 			//alert("Branch==>"+branch.value+" Product id===> "+selprodid);
  		
	 		var url = "getPREFilesPreprocessAction.do?instid="+instid+"&branchcode="+branch.value+"&prodid="+prodid+"&filetype="+filetype.value;
	 		//alert(url);
	 		result = AjaxReturnValue(url);  
	 		document.getElementById("prefilename").innerHTML = result;  
	 		document.getElementById("prefileview").style.display="none";
 		}
 		
 		
 	}
 	function getPREFiles( instid,selprodid ){
 		var branch = document.getElementById("branchcode");
 		var filetype = document.getElementById("filetype");
 		if(branch.value == "-1")
 		{
 			errMessage( branch, "Please Select Branch " );
 			return false;	
 		}
 		if( selprodid != "-1" )
 		{
 			//alert("Branch==>"+branch.value+" Product id===> "+selprodid);
  			prodid = selprodid; 
	 		var url = "getPREFilesPreprocessAction.do?instid="+instid+"&branchcode="+branch.value+"&prodid="+prodid+"&filetype="+filetype.value;
	 		//alert(url);
	 		result = AjaxReturnValue(url);  
	 		document.getElementById("prefilename").innerHTML = result;  
	 		document.getElementById("prefileview").style.display="none";
 		}
 	}
 	
 	function Validation()
 	{
 		var branchcode = document.getElementById("branchcode");
 		var cardtype = document.getElementById("cardtype");
 		if( branchcode )
 		{
			if(branchcode.value == "-1")
			{
				errMessage(branchcode," Select Branch ");
				return false;
			}
 		}
 		if( cardtype )
 		{
 			if(cardtype.value == "-1")
 			{
 				errMessage(cardtype," Select Product ");
				return false;	
 			}
 		}
 		
 		//parent.showprocessing();

 	}
 	
 	function deletePerzonalize(){
 		if( confirm ("Do you want to delete...") ){
	 		var prefilename = document.getElementById("prefilename");
	 		var url = "deleteInstPreFilePreprocessAction.do?prefilename="+prefilename.value; 		
	 		window.location = url;
	 		parent.showprocessing();
 		}
 		return false;
 	}
 	
 	function getFileDetails( instid, filename ){
 		 
 		var prodid = document.getElementById("cardtype"); 
 		var url = "getPREFilesDetailsPreprocessAction.do?instid="+instid+"&filename="+filename+"&prodid="+prodid.value;
 		 
 		result = AjaxReturnValue(url);
 		 
 		//document.getElementById("prefilename").innerHTML = result; 
 		
 		 var jsonobj = JSON.parse(result);  
 		if( jsonobj["RESP"] != 0 ){
 			document.getElementById("prefileview").style.display="none";
 			document.getElementById("prefileview").innerHTML = "";
 		}else{
 			document.getElementById("prefileview").style.display="block";
 			 
			var divblock =" <table border='0' width='100%' cellpadding='0' cellspacing='0'>";
			divblock +="		<tr><td> Selected File name </td><td style='text-align:left'> : "+jsonobj["PRENAME"]+" </td></tr> ";
			divblock +="		<tr><td> No.of Cards Contains </td><td  style='text-align:left'> : "+jsonobj["CARDCOUNT"]+" </td></tr>";
			divblock +="		<tr><td> Generated By  </td><td  style='text-align:left'> : "+jsonobj["USERNAME"]+" </td></tr>";
			divblock +="		<tr><td> Generated Date  </td><td  style='text-align:left'> : "+jsonobj["GENDATE"]+" </td></tr>";
			divblock +="		<tr><td> Download Status </td><td  style='text-align:left'> : "+jsonobj["DOWNCNT"]+" time(s) downloaded </td></tr>";
			divblock +="	<tr><td colspan='2' onclick=showCards("+"'"+filename+"'"+")>   View List of cards  </td></tr>";
			divblock +="	</table>";
			divblock +="	</div>";
			
			document.getElementById("prefileview").innerHTML=divblock;
 		}
 	}
 	
 	function showCards( filename ){
 	 
 		var url = "getPREFileListPreprocessAction.do?filename="+filename;   
 		result = AjaxReturnValue(url);  
 		alert( result );
 		
 	}
 	
 </script>
</head>
<jsp:include page="/displayresult.jsp"></jsp:include>
<%
	String instid = (String)session.getAttribute("Instname");
%>
<s:form action="prefileDownloadPreprocessAction"  name="perscardgen" autocomplete = "off" namespace="/">

<%-- <s:form action="downloadFilePreFormatPreprocessAction"  name="perscardgen" autocomplete = "off" namespace="/"> --%>

<table border="0" cellpadding="0" cellspacing="0" width="50%" class="formtable">
	<% String usertype=(String)session.getAttribute("USERTYPE");
		if(usertype.equals("INSTADMIN"))
		{
	%>
			<tr>
				<td class="fnt"> Select Branch</td>
				<td> : <s:select name="branchcode" id="branchcode" listKey="BRANCH_CODE" listValue="BRANCH_NAME" list="branchlist"  headerValue="Select Branch" headerKey="-1"/></td>
			</tr>
	<%	
		}
		else
		{
	%>
			<tr>
			<td> Branch</td>
			<td>  <%out.println( session.getAttribute("BRANCH_DESC") ); %></td>
				<s:hidden name="branchcode" id="branchcode" value="%{#session.BRANCHCODE}" />
			</tr>
	<%		
		}
	%>
	
	<tr>
		<td class="fnt">
		Select Product
		</td>
		<td> :
 				<select name="cardtype" id="cardtype" onchange="getPREFiles('<%=instid%>',this.value)">
	 				<option value="-1">Select Product</option>
	 				<s:iterator  value="personalproductlist">
	 					<option value="${PRODUCT_CODE}">${CARD_TYPE_NAME}</option>
	 				</s:iterator>
 				</select>
		</td>
    </tr>
    
	
	 <tr>	
		<td> 
		SFTP Profile
		</td>
		<td> :  <select name="SFTP Profile" id="SFTP Profile" onchange="resetProduct('<%=instid%>',this.value)" >
					
 				</select>
		</td>
	</tr>   
	

    <tr>	
		<td> 
		Prefile Download Citeria
		</td>
		<td> :  <select name="prefilename" id="prefilename" onchange="getFileDetails('<%=instid%>',this.value)" > 
 				</select>
		</td>
	</tr>   
	
	<tr>
	   <td align="left" class="fnt">From Date<font class="mand">*</font></td>
		<td> :
		<input type="text" name="fromdate" id="fromdate"  readonly="readonly" onchange="return yearvalidation(this.id);" style="width:160px">
		<img src="style/images/cal.gif" id="image" onclick="displayCalendar(document.perscardgen.fromdate,'dd-mm-yy',this);" title="Click Here to Pick up the date" border="0" width="15" height="17">
		</td>
	</tr>
	<tr>
	    <td align="left" class="fnt">To Date <font class="mand">*</font></td>
		<td> :
		<input type="text" name="todate" id="todate"  readonly="readonly" onchange="return yearvalidation(this.id);" style="width:160px">
		<img src="style/images/cal.gif" id="image" onclick="displayCalendar(document.perscardgen.todate,'dd-mm-yy',this);" title="Click Here to Pick up the date" border="0" width="15" height="17">
		</td>
	</tr>
	 
</table>
<table border="0" cellpadding="0" cellspacing="10" width="20%" >
		<tr>
		<td>
			<s:submit value="Download" name="Download" id="Download" onclick="return Validation();"/>
		</td>
		<td>
			<input type="button" name="cancel" id="cancel" value="Cancel"  class="cancelbtn"  onclick="return confirmCancel()"/>
			 
		</td>
		
		<td>
			<input type="submit" name="submit" id="delete" value="Delete" onclick="return deletePerzonalize()"  />
			 
		</td>
		
		
		</tr>
</table>

</s:form>
